---
- name: Install set keymaps (don't forget to set once booted!)
  become: true
  shell: |
    wget https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.5.1.tar.gz -O /tmp/kbd-2.5.1.tar.gz \
      && cd /tmp/ && tar xzf kbd-2.5.1.tar.gz \
      && mkdir -p /usr/share/keymaps \
      && cp -Rp /tmp/kbd-2.5.1/data/keymaps/* /usr/share/keymaps/ \
      && if $(systemd-notify --booted); then localectl set-keymap us; else echo "System not booted using systemd; unable to set keymaps using localectl. Remember to do this later"; fi

- name: Set timezone
  become: true
  shell: if $(systemd-notify --booted); then timedatectl set-timezone Europe/London; fi

- name: Enable gdm on startup
  become: true
  ansible.builtin.shell: |
    if $(systemd-notify --booted); then systemctl enable gdm; else echo "System not booted using systemd; unable to enable GDM on startup. Remember to do this later"; fi

- name: Enable Docker on startup
  become: true
  ansible.builtin.shell: |
    if $(systemd-notify --booted); then systemctl enable --now docker.service; else echo "System not booted using systemd; unable to enable Docker on startup. Remember to do this later"; fi

- name: Add user to Docker group
  become: true
  ansible.builtin.shell: |
    usermod -aG docker $USER

- name: Install dotfiles
  shell: "yadm clone -f {{ DOTFILES_REPO }}"
