---
- name: Install Arch system packages (batch 1)
  become: true
  ansible.builtin.package:
    name:
      # Audio
      - alsa-lib
      - libpulse
      - libnl
      - libxcb
      - pavucontrol
      - pulseaudio
      - pulseaudio-alsa
      # Video
      - v4l2loopback-dkms
      - v4l2loopback-dc-dkms
      - v4l2loopback-utils
      - v4l-utils
      # Browsers
      - chromium
      # Database
      - dbeaver
      - postgresql
      # Email
      - neomutt
      # Shell
      - bash
      - bash-completion
      - terminator
      - yadm

- name: Install Arch system packages (batch 2)
  become: true
  ansible.builtin.package:
    name:
      # Desktop
      - dunst
      - feh
      - gdm
      - i3
      - i3lock
      - lxappearance
      - network-manager-applet
      - noto-fonts-emoji
      - picom
      - polybar
      - python-i3ipc
      - rofi
      - unclutter
      - xdotool
      - xss-lock
      # Docker
      - docker
      - docker-compose
      - kompose
      - kubectl
      - minikube
      # Languages
      - go
      - jdk8-openjdk
      - jdk11-openjdk
      - jdk17-openjdk
      - jdk21-openjdk
      - llvm
      - lua
      - luarocks
      - maven
      - nodejs
      - npm
      - rust
      - rustup

- name: Install Arch system packages (batch 3)
  become: true
  ansible.builtin.package:
    name:
      # Core
      - linux-headers
      - apache
      - cmake
      - clang
      - curl
      - wget
      - git
      - unzip
      - ninja
      - ca-certificates
      - gnupg
      - alsa-utils
      - base-devel
      - bzip2
      - clang
      - cmake
      - cronie
      - gawk
      - gcc
      - gnome-keyring
      - gvfs
      - keychain
      - libnghttp2
      - libxcb
      - linux-tools
      - lsof
      - xorg-setxkbmap
      - xcape
      - make
      - openssl
      - patch
      - systemd
      - time
      - tree
      - which
      - zip
      - zlib

- name: Install Arch system packages (batch 4)
  become: true
  ansible.builtin.package:
    name:
      # Utils
      - tmux
      - python-libtmux
      - exa
      - fzf
      - bat
      - btop
      - broot
      - thefuck
      - httpie
      - ripgrep
      - diff-so-fancy
      - tldr
      - yank
      - colordiff
      - fd
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-ugly
      - jq
      - mkcert
      - certbot
      - certbot-nginx
      - nnn
      - ranger
      - neofetch
      - lazygit
      - net-tools
      - whois
      - traceroute
      - dnsutils
      - tcpdump
      - nmap
      - ueberzug
      - maim

- name: Install yay AUR package manager
  ansible.builtin.shell: |
    git clone https://aur.archlinux.org/yay-bin.git \
      && cd yay-bin \
      && makepkg -si --noconfirm \
      && cd .. \
      && rm -rf yay-bin

- name: Install packages from AUR (1)
  shell: |
    yes | yay -Syu --noconfirm --answerdiff=None \
      azure-cli-bin \
      firefox \
      i3-resurrect \
      lazydocker \
      splatmoji-git \
      makepasswd

- name: Install packages from AUR (2)
  shell: |
    yes | yay -Syu --noconfirm --answerdiff=None \
      mongodb-compass \
      mongosh \
      mssql-tools \
      mycli

- name: Install packages from AUR (3)
  shell: |
    yes | yay -Syu --noconfirm --answerdiff=None \
      neovim-git \
      neovim-remote

- name: Install other packages
  shell: |
    # ble.sh
    mkdir -p ~/.local/share/blesh && wget -qO- https://github.com/akinomyoga/ble.sh/releases/download/v0.3.4/ble-0.3.4.tar.xz | tar -C ~/.local/share/blesh --strip-components=1 -xJvf-
    # mcfly
    curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh --force | sh -s -- --git cantino/mcfly
    # doppler
    curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sudo sh

- name: Install NPM packages
  become: true
  ansible.builtin.shell: |
    npm install --global \
    @fsouza/prettierd \
    @tailwindcss/language-server \
    eslint \
    eslint_d \
    git-cz \
    n \
    prettier \
    redis-cli \
    tree-sitter-cli \
    ts-node \
    typescript \
    typescript-language-server \
    vscode-langservers-extracted \
    yarn

- name: Install Cargo packages
  ansible.builtin.shell: |
    cargo install \
      cargo-edit \
      cargo-tarpaulin \
      cargo-watch \
      cargo-audit \
      cargo-expand \
      hyperfine

- name: Install NVM
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sudo bash

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Install lazygit
  become: true
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') \
      && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" \
      && tar xf lazygit.tar.gz lazygit \
      && install lazygit /usr/local/bin

- name: Install Bitwarden CLI
  become: true
  ansible.builtin.shell: |
    bwVersion="2022.11.0"
    bwFilename="bw-linux-${bwVersion}.zip"
    bwZipUri="https://github.com/bitwarden/clients/releases/download/cli-v${bwVersion}/${bwFilename}"

    curl -LJO $bwZipUri  \
        && unzip ${bwFilename} \
        && rm -f ${bwFilename} \
        && chmod 755 bw \
        && mv bw /usr/local/bin/bw

- name: Install rclone
  become: true
  ansible.builtin.shell: |
    curl https://rclone.org/install.sh | bash

- name: Install Packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Install Node.js debugger
  become: true
  ansible.builtin.shell: |
    rm -rf ~/.local/share/nvim/site/pack/packer/opt/vscode-js-debug \
    && git clone https://github.com/microsoft/vscode-js-debug ~/.local/share/nvim/site/pack/packer/opt/vscode-js-debug \
    && cd ~/.local/share/nvim/site/pack/packer/opt/vscode-js-debug \
    && npm install && npm run compile vsDebugServerBundle && mv dist out

- name: Install protobufs
  ansible.builtin.shell: |
    pbVersion="3.18.0"
    pbFilename="protoc-${pbVersion}-linux-x86_64.zip"
    pbZipUri="https://github.com/protocolbuffers/protobuf/releases/download/v${pbVersion}/${pbFilename}"

    curl -LJO $pbZipUri  \
        && unzip ${pbFilename} -d ~/.local/bin/protobuf

    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

- name: Install Terraform
  ansible.builtin.shell: |
    tfVersion="1.7.3"
    tfFilename="terraform_${tfVersion}_linux_amd64.zip"
    tfZipUri="https://releases.hashicorp.com/terraform/${tfVersion}/${tfFilename}.zip"

    curl -LJO $tfZipUri  \
        && unzip ${tfFilename} \
        && rm -f ${tfFilename} \
        && chmod 755 terraform/terraform \
        && mv terraform/terraform /usr/local/bin/terraform \
        && rm -rf terraform

- name: Download Intellij tarball
  ansible.builtin.get_url:
    url: "https://download.jetbrains.com/idea/ideaIU-2023.3.6.tar.gz"
    dest: "{{ HOME }}/ideaIU.tar.gz"

- name: Create Intellij install directory
  become: true
  ansible.builtin.file:
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    path: /opt/idea

- name: Install Intellij
  become: true
  ansible.builtin.unarchive:
    src: "{{ HOME }}/ideaIU.tar.gz"
    dest: /opt/idea
    owner: "{{ USER }}"
    group: "{{ USER }}"
    extra_opts: [--strip-components=1]
