---
- name: Ensure .ssh directory exists and has correct permissions
  become: true
  file:
    dest: "{{ SSH_KEY_DST | dirname }}"
    mode: 700
    group: "{{ USER }}"
    owner: "{{ USER }}"
    state: directory

- name: Copy private SSH key into memory
  become: true
  ansible.builtin.slurp:
    src: "{{ SSH_KEY_SRC }}"
  register: slurped_private_key_file
  delegate_to: localhost

- name: Write private SSH key
  become: true
  ansible.builtin.copy:
    dest: "{{ SSH_KEY_DST }}"
    group: "{{ USER }}"
    mode: 600
    owner: "{{ USER }}"
    content: "{{ slurped_private_key_file['content'] | b64decode }}"

- name: Copy public SSH key into memory
  become: true
  ansible.builtin.slurp:
    src: "{{ SSH_KEY_SRC }}.pub"
  register: slurped_public_key_file

- name: Write public SSH key
  become: true
  ansible.builtin.copy:
    dest: "{{ SSH_KEY_DST }}.pub"
    group: "{{ USER }}"
    mode: 600
    owner: "{{ USER }}"
    content: "{{ slurped_public_key_file['content'] | b64decode }}"

- name: Set authorised SSH key
  become: true
  authorized_key:
    user: "{{ USER }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_rsa.pub') }}"
  with_fileglob:
    - "{{ HOME }}/.ssh/*.pub"
